spring:
  thymeleaf:
    cache: false
  security:
    oauth2:
      client:
        registration:
          okta:
            client-id: 0oaglz3y4mFCzB0Ep0h7
            client-secret: K2-mqE1CXgNWPoQqWUWQpLEN7vgPJPRJj0wMSETM
        provider:
          okta:
            authorization-uri: https://dev-825057.oktapreview.com/oauth2/default/v1/authorize
            token-uri: https://dev-825057.oktapreview.com/oauth2/default/v1/token
            user-info-uri: https://dev-825057.oktapreview.com/oauth2/default/v1/userinfo
            jwk-set-uri: https://dev-825057.oktapreview.com/oauth2/default/v1/keys







